version: '3.7'

services:
  testpostgresdb:
    image: postgres:15
    container_name: testpostgresdb
    environment:
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    restart: always
    ports:
      - "${POSTGRES_DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  testmongodb:
    image: mongo:7.0
    container_name: testmongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
    restart: always
    ports:
      - "${MONGO_DB_PORT}:27017"
    volumes:
      - mongodb_data:/data/db
    command: ["--auth"]
  testredis:
    image: redis:7.4.0
    container_name: testredis
    ports:
      - "${REDIS_PORT}:6379"
    restart: always
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  mongodb_data:
  redis_data: